-- H2 2.2.224;
CREATE USER IF NOT EXISTS "SA" SALT 'eb6f50c96993c665' HASH 'e3fd1788e1e89b6bcba52625a0229016948ec54959ce78dd740bc8d1a2d9ff67' ADMIN;
CREATE SEQUENCE "PUBLIC"."OBJECTIVE_DATA_SEQ" START WITH 1 RESTART WITH 351 INCREMENT BY 50;
CREATE MEMORY TABLE "PUBLIC"."OBJECTIVE_DATA"(

    "TEAM_NUMBER" INTEGER,
	"MATCH_TYPE" CHARACTER VARYING(255),
	"DATA_QUALITY" INTEGER,
	"MATCH_NUMBER" INTEGER,
	"REPLAY" BOOLEAN,
	"ALLIANCE_COLOR" CHARACTER VARYING(255),
	"DRIVER_STATION" INTEGER,
	"SCOUTER_NAME" CHARACTER VARYING(255),
	"PRELOAD" BOOLEAN,
	"START_POS" CHARACTER VARYING(255),
	"LEFT_WING" BOOLEAN,
	"AUTO_SPEAKER" INTEGER,
	"AUTO_AMP" INTEGER,
	"AUTO_PICK_UP_WING" INTEGER,
	"AUTO_PICK_UP_CENTER" INTEGER,
    "A_STOP" BOOLEAN,
	"PICK_UP_GROUND" INTEGER,
	"PICK_UP_SOURCE" INTEGER,
	"SPEAKER_NOTES_UNAMPED" INTEGER,
	"SPEAKER_NOTES_AMPED" INTEGER,
    "AMP_NOTES" INTEGER,
	"FEEDER" BOOLEAN,
    "COOPERTITION" BOOLEAN,
    "ONSTAGE" BOOLEAN,
    "PARK" BOOLEAN,
    "SPOTLIGHT" BOOLEAN,
    "TRAP" BOOLEAN,
    "COMMENTS" CHARACTER VARYING(512),
	"ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."OBJECTIVE_DATA" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.OBJECTIVE_DATA;